[[Templates]]
Name="testtemplate"
Description="test dsec"
Topic="test Topic"
Disabled=false
TTLInSeconds=3600
Delivery="tencentcloudsms"
Engine="handlebars"
[[Template.Constants]]
"a"="15"
"b"="22"
[[Template.Params]]
Source="userinfo"
target="user"
Parser="json"
Description="用户信息"
Example='''{"id":12345,"name":"abcd"}'''
[[Template.Params]]
Source="mobile"
Description="手机号"
Example="13500000000"
[[Template.Params]]
Source="usercode"
Target="code"
Description="验证码"
Example="abcdefg"
[Template.HeaderTemplate]
"target"="{{{user.id}}}"
[Template.ContentTemplate]
"templatecode"="123456"
"phonenumbers"="+86{{{commaescape mobile}}}"
"templatparams"="{{{commaescape code}}}"
